//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ODMSBIEntities : DbContext
    {
        public ODMSBIEntities()
            : base("name=ODMSBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("ODMSBIEntities", "FunctionStringtoIntlist")]
        public virtual IQueryable<FunctionStringtoIntlist_Result> FunctionStringtoIntlist(string list, string delim)
        {
            var listParameter = list != null ?
                new ObjectParameter("list", list) :
                new ObjectParameter("list", typeof(string));
    
            var delimParameter = delim != null ?
                new ObjectParameter("delim", delim) :
                new ObjectParameter("delim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FunctionStringtoIntlist_Result>("[ODMSBIEntities].[FunctionStringtoIntlist](@list, @delim)", listParameter, delimParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_BuyerByDBDetails_Result> RPT_Delivery_BuyerByDBDetails(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_BuyerByDBDetails_Result>("RPT_Delivery_BuyerByDBDetails", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_BuyerByDBsOutletList_Result> RPT_Delivery_BuyerByDBsOutletList(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_BuyerByDBsOutletList_Result>("RPT_Delivery_BuyerByDBsOutletList", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_BuyerByDBSummary_Result> RPT_Delivery_BuyerByDBSummary(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_BuyerByDBSummary_Result>("RPT_Delivery_BuyerByDBSummary", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_BuyerByPSRDetails_Result> RPT_Delivery_BuyerByPSRDetails(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_BuyerByPSRDetails_Result>("RPT_Delivery_BuyerByPSRDetails", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_BuyerByPSRsOutletList_Result> RPT_Delivery_BuyerByPSRsOutletList(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string psrids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var psridsParameter = psrids != null ?
                new ObjectParameter("Psrids", psrids) :
                new ObjectParameter("Psrids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_BuyerByPSRsOutletList_Result>("RPT_Delivery_BuyerByPSRsOutletList", start_DateParameter, end_DateParameter, psridsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_BuyerByPSRSummary_Result> RPT_Delivery_BuyerByPSRSummary(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_BuyerByPSRSummary_Result>("RPT_Delivery_BuyerByPSRSummary", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_DBPerformanceKPISummary_Result> RPT_Delivery_DBPerformanceKPISummary(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_DBPerformanceKPISummary_Result>("RPT_Delivery_DBPerformanceKPISummary", start_DateParameter, end_DateParameter, dbidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_NonBuyerByDBsOutletList_Result> RPT_Delivery_NonBuyerByDBsOutletList(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_NonBuyerByDBsOutletList_Result>("RPT_Delivery_NonBuyerByDBsOutletList", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_NonBuyerByPSRsOutletList_Result> RPT_Delivery_NonBuyerByPSRsOutletList(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string psrids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var psridsParameter = psrids != null ?
                new ObjectParameter("Psrids", psrids) :
                new ObjectParameter("Psrids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_NonBuyerByPSRsOutletList_Result>("RPT_Delivery_NonBuyerByPSRsOutletList", start_DateParameter, end_DateParameter, psridsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_OutletWiseSKUWiseDelivery_Result> RPT_Delivery_OutletWiseSKUWiseDelivery(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_OutletWiseSKUWiseDelivery_Result>("RPT_Delivery_OutletWiseSKUWiseDelivery", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual int RPT_Delivery_OutletWiseSummary(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RPT_Delivery_OutletWiseSummary", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Order_OutletWiseSKUWiseOrder_Result> RPT_Order_OutletWiseSKUWiseOrder(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Order_OutletWiseSKUWiseOrder_Result>("RPT_Order_OutletWiseSKUWiseOrder", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_Order_PSRWiseSKUWiseOrder_Result> RPT_Order_PSRWiseSKUWiseOrder(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Order_PSRWiseSKUWiseOrder_Result>("RPT_Order_PSRWiseSKUWiseOrder", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_StockMovement_Result> RPT_StockMovement(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, Nullable<int> dbid)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidParameter = dbid.HasValue ?
                new ObjectParameter("dbid", dbid) :
                new ObjectParameter("dbid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_StockMovement_Result>("RPT_StockMovement", start_DateParameter, end_DateParameter, dbidParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_PSRPerformanceKPISummary_Result> RPT_Delivery_PSRPerformanceKPISummary(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_PSRPerformanceKPISummary_Result>("RPT_Delivery_PSRPerformanceKPISummary", start_DateParameter, end_DateParameter, dbidsParameter);
        }
    
        public virtual ObjectResult<RPT_Delivery_PSRWiseSKUWiseDelivery_Result> RPT_Delivery_PSRWiseSKUWiseDelivery(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string skuids)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var skuidsParameter = skuids != null ?
                new ObjectParameter("skuids", skuids) :
                new ObjectParameter("skuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Delivery_PSRWiseSKUWiseDelivery_Result>("RPT_Delivery_PSRWiseSKUWiseDelivery", start_DateParameter, end_DateParameter, dbidsParameter, skuidsParameter);
        }
    
        public virtual ObjectResult<RPT_TP_Summary_Result> RPT_TP_Summary(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string promo_id)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var promo_idParameter = promo_id != null ?
                new ObjectParameter("Promo_id", promo_id) :
                new ObjectParameter("Promo_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_TP_Summary_Result>("RPT_TP_Summary", start_DateParameter, end_DateParameter, dbidsParameter, promo_idParameter);
        }
    
        public virtual ObjectResult<RPT_TP_OutletWiseDetails_Result> RPT_TP_OutletWiseDetails(Nullable<System.DateTime> start_Date, Nullable<System.DateTime> end_Date, string dbids, string promo_id)
        {
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(System.DateTime));
    
            var dbidsParameter = dbids != null ?
                new ObjectParameter("dbids", dbids) :
                new ObjectParameter("dbids", typeof(string));
    
            var promo_idParameter = promo_id != null ?
                new ObjectParameter("Promo_id", promo_id) :
                new ObjectParameter("Promo_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_TP_OutletWiseDetails_Result>("RPT_TP_OutletWiseDetails", start_DateParameter, end_DateParameter, dbidsParameter, promo_idParameter);
        }
    }
}
