//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_db_psr_outlet_zone_view
    {
        public Nullable<int> DB_Id { get; set; }
        public string DB_Name { get; set; }
        public Nullable<int> CEAREA_id { get; set; }
        public string CEAREA_Name { get; set; }
        public Nullable<int> AREA_id { get; set; }
        public string AREA_Name { get; set; }
        public Nullable<int> REGION_id { get; set; }
        public string REGION_Name { get; set; }
        public Nullable<int> National_id { get; set; }
        public string National { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public Nullable<int> PSR_id { get; set; }
        public string PSR_Code { get; set; }
        public string DBCode { get; set; }
        public string OfficeAddress { get; set; }
        public string cluster { get; set; }
        public string RouteName { get; set; }
        public int RouteID { get; set; }
        public int OutletId { get; set; }
        public string OutletCode { get; set; }
        public string OutletName { get; set; }
        public string OutletName_b { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string GpsLocation { get; set; }
        public string OwnerName { get; set; }
        public string ContactNo { get; set; }
        public int Distributorid { get; set; }
        public int HaveVisicooler { get; set; }
        public int parentid { get; set; }
        public int outlet_category_id { get; set; }
        public int grading { get; set; }
        public int channel { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string picture { get; set; }
        public int IsActive { get; set; }
        public string channel_name { get; set; }
        public string outlet_category_name { get; set; }
        public string Outlet_grade { get; set; }
    }
}
